apiVersion: v1
kind: ConfigMap
metadata:
  name: limesurvey-config
data:
  config.php: |
    <?php if (!defined('BASEPATH')) exit('No direct script access allowed');
    return array(
      'components' => array(
        'db' => array(
          'connectionString' => '{{ .Values.externalDatabase.type }}:host={{ .Values.externalDatabase.host }};port={{ .Values.externalDatabase.port }};dbname={{ .Values.externalDatabase.database }}',
          'emulatePrepare' => true,
          'username' => getenv('DB_USERNAME'),
          'password' => getenv('DB_PASSWORD'),
          'charset' => 'utf8',
          'tablePrefix' => 'lime_',
        ),
        'urlManager' => array(
          'urlFormat' => 'path',
          'rules' => array(),
          'showScriptName' => true,
        ),
        'request' => array(
          'baseUrl' => '',
        ),
      ),
      'config'=>array(
        'publicurl'=>'',
        'debug'=>0,
        'debugsql'=>0,
        'mysqlEngine' => 'MyISAM',
      )
    );
