apiVersion: v1
kind: ConfigMap
metadata:
  name: limesurvey-config
data:
  config.php: |
    <?php if (!defined('BASEPATH')) exit('No direct script access allowed');
    return array(
      'components' => array(
        'db' => array(
          'connectionString' => '{{ .Values.externalDatabase.type }}:host={{ .Values.externalDatabase.host }};port={{ .Values.externalDatabase.port }};dbname={{ .Values.externalDatabase.database }}',
          'emulatePrepare' => true,
          'username' => getenv('DB_USERNAME'),
          'password' => getenv('DB_PASSWORD'),
          'charset' => 'utf8',
          'tablePrefix' => 'lime_',
        ),
        'urlManager' => array(
          'urlFormat' => 'path',
          'rules' => array(),
          'showScriptName' => true,
        ),
        'request' => array(
          'baseUrl' => '',
        ),
      ),
      'config'=>array(
        'publicurl'=>'',
        'debug'=>0,
        'debugsql'=>0,
        'mysqlEngine' => 'MyISAM',
      )
    );


    externalDatabase:
  # Type of external database ("mysql" or "pgsql")
  type: mysql
  # External Database server host
  host: mariadb.example.com
  # External Database server port
  port: 3306
  # External Database username (use existingSecretConfig.usernameField to load from secret)
  username: limesurvey
  # External Database user password
  # (ignored when existingSecret is set, use existingSecretConfig.passwordField to change key)
  password: null
  # External Database database name (use existingSecretConfig.databaseField to load from secret)
  database: limesurvey
  # Use an existing secret for retrieving the database password.
  # The secret must contain the field "db-password" (field name configurable via existingSecretConfig.passwordField)
  existingSecret: null
  existingSecretConfig:
    passwordField: db-password
    usernameField: null
    databaseField: null