apiVersion: v2
name: limesurvey
description: Limesurvey is the number one open-source survey software.
type: application
version: 0.8.9
appVersion: "5-apache"
maintainers:
  - email: carsten.scharfenberg@zalf.de
    name: Carsten scharfenberg
sources:
  - https://github.com/fairagro/limesurvey-helm
  - https://github.com/martialblog/helm-charts
  - https://github.com/martialblog/docker-limesurvey/
  - https://limesurvey.org/
